### ISSUE TITLE
experiment

### ISSUE THREAD

**Issue by yanxinhao** [chenhsuanlin/bundle-adjusting-NeRF#1]
could you please share the code of "Planar Image Alignment" Experiment ? Thanks

**Comment by chenhsuanlin** [comment]
Sure, I'll release it hopefully in a week or so. Leaving this issue open for now.

**Comment by ivasiljevic** [comment]
@chenhsuanlin any updates on this experiment? :)

**Comment by chenhsuanlin** [comment]
Hi @yanxinhao @ivasiljevic, very sorry for getting to this late. I've added the planar image alignment experiments; please see the updated README for more details.
Closing this issue for now, but please feel free to reopen anytime if you have further questions!

**Comment by yanxinhao** [comment]
haha, thank you! great work
