### ISSUE TITLE
Multiprocessing issue on Windows

### ISSUE THREAD

**Issue by szymanowiczs** [chenhsuanlin/bundle-adjusting-NeRF#10]
Hi Chen-Suan,

There is an issue with multiprocessing on Windows (see screenshot below). Wrapping the functions in train.py and evaluate.py with a main() function resolves them.  I made a PR that resolves this issue: https://github.com/chenhsuanlin/bundle-adjusting-NeRF/pull/11 

Let me know if you think you can merge it into main :)

Kind regards,
Stan
![issue_mp](https://user-images.githubusercontent.com/23418488/146186491-30b62e1b-7cea-49ce-8b52-ba152a8d2969.PNG)

**Comment by chenhsuanlin** [comment]
Merged into main, I didn't realize this was an issue on Windows. Thanks @szymanowiczs for the PR!
