### ISSUE TITLE
Image from validation cameras 'moves away'

### ISSUE THREAD

**Issue by szymanowiczs** [chenhsuanlin/bundle-adjusting-NeRF#13]
Hi Chen-Hsuan,

Thanks for the great work. 
Every time the validation code is run, the resulting renders seem to move away from the camera (see images).
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/23418488/146193104-06ff9881-21a1-41ea-a827-9f99aafc0277.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/23418488/146193114-7ae3c165-49ce-4ee3-846f-c18678f7ebeb.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/23418488/146193130-4ec19a4f-f925-45a9-99fe-e647ef322aab.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/23418488/146193150-702c1b8b-b14e-4fda-8621-7587363a3bbe.png)

The underlying reason is that the arguments passed to preprocess_camera.py are passed by reference, so preprocess_camera.py changes the intrinsics of the underlying camera. This change occurs every time the validation code is run, so the intrinsics change, and the validation images become smaller and smaller. To avoid this issue, I have created a PR that detaches and clones the pose before preprocessing, therefore passing a copy of the intrinsics to be modified appropriately. https://github.com/chenhsuanlin/bundle-adjusting-NeRF/pull/12

Let me know if we can pull this into main - it avoids the objects 'moving away', making the validation images easier to analyse.   

Kind regards,
Stan

**Comment by chenhsuanlin** [comment]
Thanks @szymanowiczs for the great catch! I've modified your PR to clone the variables (no need to detach) in `preprocess_camera()` instead -- ideally variables shouldn't be modified in-place here.
