### ISSUE TITLE
Launching experiments in AzureML

### ISSUE THREAD

**Issue by szymanowiczs** [chenhsuanlin/bundle-adjusting-NeRF#15]
Hi Chen-Hsuan,

Thanks for the great repo and a great piece of research! I think it would have even more impact if any user who wants to try it could launch training in the cloud, with automated hyperparameter sampling.

I have just made a PR which includes all the necessary infrastructure to be able to launch experiments in AzureML https://github.com/chenhsuanlin/bundle-adjusting-NeRF/pull/14. This should enable faster and easier experimentation with your code for anyone who might want to use it. Let me know if you have any suggestions of how to make the PR better.

Best wishes,
Stan

**Comment by chenhsuanlin** [comment]
Hi @szymanowiczs, thanks for the PR!
Adding AzureML support sounds very nice. However, I'm not using AzureML at the moment and won't be able to verify the functionality of the PR. Also, I would prefer to keep the main branch as lightweight as possible with minimal overhead of using the code. I'm happy to mention AzureML support and link to your branch in the README, but I probably won't merge it into main at this time. Hope this makes sense to you!

**Comment by szymanowiczs** [comment]
All makes sense, thank you!
