### ISSUE TITLE
camera pose refinement starting from relatively correct initial poses instead of identity transformation matrices

### ISSUE THREAD

**Issue by tofis** [chenhsuanlin/bundle-adjusting-NeRF#20]
Thank you @chenhsuanlin for sharing this impressive work.  I wanted to ask you whether it is possible to initiate BARF training from initial camera poses instead of identity matrices changing the configuration only or I have to adapt the code.

**Comment by chenhsuanlin** [comment]
Hi @tofis, it is definitely possible (as was in the Blender data experiments), but there would be a bit of code modification involved. The `pose` variable up to [this line](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/barf.py#L220) would be the initial poses (ground truth + noise for Blender and identity for LLFF), followed by the correction `pose_refine`. So you just have to make sure your initial camera poses are assigned to `pose`.
Hope this helps!

**Comment by tofis** [comment]
Thanks for the prompt reply! Indeed, that does the job!
