### ISSUE TITLE
Camera Pose Optimization with Geometry Prior

### ISSUE THREAD

**Issue by satyajitghana** [chenhsuanlin/bundle-adjusting-NeRF#30]
Hey,

I am trying to optimize the camera positions given a non textured mesh. Right now NeRF implementation does not consider this prior and samples random rays. I was wondering how do I provide my mesh as initial input to BARF? Since I already have the mesh it should be instant to fix the camera poses! 

I've tried to use PyTorch3D as differentiable renderer with BARF's additional parameters for camera pose optimisation, but it doesn't work. The cameras drift away and loss becomes NaN.

**Comment by chenhsuanlin** [comment]
Hi @satyajitghana, I'm not sure how you're incorporating 3D meshes into the NeRF/BARF framework; this seems nontrivial to me. If you're building your work upon PyTorch3D, I would suggest contacting the PyTorch3D team for issues.

**Comment by satyajitghana** [comment]
I'm using a differentiable renderer to render the scene and then comparing with the camera image. This process didn't work.

I haven't incorporated 3D mesh into NeRF, i was hoping you could guide me on how it could be done.

**Comment by chenhsuanlin** [comment]
One possible way of utilizing a given 3D mesh in NeRF is to render the mesh depth and use it as a prior for volume rendering sampling, in which case would be (almost) equivalent to mesh rendering if the samples were fully concentrated on the mesh surfaces. Therefore, if you're working on a setup where BARF is expected to work (e.g. with sufficiently well-initialized poses), then I would expect PyTorch3D to work as well. If you're looking specifically for a coarse-to-fine solution for mesh-based inverse optimization, I would suggest looking into [Soft Rasterizer](https://github.com/ShichenLiu/SoftRas), which is the baseline PyTorch3D improves upon.

**Comment by satyajitghana** [comment]
Soft Rasterizer seems promising, saw an example of pose optimisation of cube, I'll try it out on my model !
