### ISSUE TITLE
Training BARF with another real data 

### ISSUE THREAD

**Issue by wbjang** [chenhsuanlin/bundle-adjusting-NeRF#32]
Hello Chen-Hsuan,

Thank you again for releasing the code.
I have tried to train BARF with Freiburg Cars dataset. (please see the attached mp4 file)
As you can see, it is a real dataset with a spherical sequence. (hybrid between LLFF and NeRF-Synthetic)

I ran COLMAP to obtain camera pose, and have tried to train the model but it was not successful.
I have tried

1) Starting from zero 6-dimensional se3 vectors (as in LLFF), but the model could not find the proper pose. 
2) Adding noise (0.15) from the GT pose, but the error on Rotation and Translation keeps increasing. As far as I know, the model finds the correct pose first and optimizes the NeRF parameters - but they do not work. Please see the images. Validation error keeps increasing as the pose estimation was not successful. 

Separately, NeRF could be trained with this dataset successfully. 
Please advise me on how I should do with this.

Cheers,
Wonbong

https://user-images.githubusercontent.com/32883157/165571787-dc6c6ec7-ba8a-4a9d-8bd9-01a7da850ae5.mp4

![Screenshot from 2022-04-27 17-50-05](https://user-images.githubusercontent.com/32883157/165577907-0e42ec40-a5fd-40c1-bcf5-a52a9050ee1f.png)
![Screenshot from 2022-04-27 17-55-06](https://user-images.githubusercontent.com/32883157/165579084-0e14b667-588a-4115-a6aa-b0680a79ce3c.png)

**Comment by wbjang** [comment]
Hello Chen-Hsuan, 

I found out that the scale plays an important role here. For GT pose + noise, normalizing camera locations (as well as query points) is helpful.  The Freiburg Cars dataset is an unbounded scene, - so the scale from the GT pose is larger than 5.

I am still looking at starting from zero initialization.

Cheers,
Wonbong

**Comment by chenhsuanlin** [comment]
Hi @wbjang, it seems that your sequence was captured object-centric with unbounded background. I don't think BARF will be able to automatically spread out the cameras to 360˚ from scratch as it's still a local registration method. You may also want to check out how [Mip-NeRF 360](https://jonbarron.info/mipnerf360) parametrizes unbounded 3D spaces and see if BARF can be an add-on.
The other problem I can see is the dynamic objects in the sequence (e.g. moving cars). NeRF may be able to tolerate such noises if it were not too severe, but I haven't analyzed how robust BARF is to noises. This is probably an issue as well.

Hope this helps!

**Comment by wbjang** [comment]
Hi @chenhsuanlin, thank you very much for your kind answer and suggestion!
