### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by samcao416** [chenhsuanlin/bundle-adjusting-NeRF#38]
Hi! Thank you for sharing your fantastic work!
When I was trying to train the network with a 3090 in barf mode with position encoding with blender datasets, after validating, it always show that
RuntimeError: CUDA out of memory. Tried to allocate 5.25 GiB (GPU 0; 23.70 GiB total capacity; 15.75 GiB already allocated; 4.71 GiB free; 15.77 GiB reserved in total by PyTorch)
Could you please tell me which parameter I should change to avoid this problem? Thank you very much!

**Comment by chenhsuanlin** [comment]
Hi @samcao416, you could try adding `torch.cuda.empty_cache()`, but this shouldn't really be needed as the default commands in the README should fit even in a 12GB GPU. Are you running the commands exactly as in the README?

**Comment by samcao416** [comment]
> Hi @samcao416, you could try adding `torch.cuda.empty_cache()`, but this shouldn't really be needed as the default commands in the README should fit even in a 12GB GPU. Are you running the commands exactly as in the README?

Yes, I use the command 
` python3 train.py --group=<GROUP> --model=barf --yaml=barf_blender --name=<NAME> --data.scene=<SCENE> --barf_c2f=[0.1,0.5] `
The only difference is that I prepared my own data in the blender format. I downscale the image to 960*540 (also changed the  images' H and W in nerf_blender.yaml). The training image has 680 views, could it be the problem? Besides, I found that before the first validating procedure, about 7GB of memory was used. But after the validation, when ` [val] loss: 9.957e-02 ` showed, the memory usage increased to about 20GB. 
I will take your advice and try to add ` torch.cuda.empty_cache() ` after the validation. If I have any progress, I will let you know.
Thanks a lot!

**Comment by samcao416** [comment]
> Hi @samcao416, you could try adding `torch.cuda.empty_cache()`, but this shouldn't really be needed as the default commands in the README should fit even in a 12GB GPU. Are you running the commands exactly as in the README?

Maybe I input too much images or the training images are too large. I just tried the hotdog dataset, and during the validation, it took about 3GB of memory. Afterward, the usage grew up to about 6GB.

**Comment by chenhsuanlin** [comment]
Yes, there are too many training images in your data. This codebase randomly samples the rays from all training images, so it prefetches and fits all training data into the GPU (see [here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L28-L30) and [here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L58-L60)). You'll need to either host your images on CPU instead, and/or modify the training loop to batch the training images to GPU instead.
