### ISSUE TITLE
How was focal length calculated for the iPhone 12 in the example?

### ISSUE THREAD

**Issue by reynoldscem** [chenhsuanlin/bundle-adjusting-NeRF#39]
In the example in `data/iphone.py` the focal length is computed as `self.focal = self.raw_W * 4.2 / (12.8 / 2.55)`. I am wondering what the specific constants mean?

**Comment by reynoldscem** [comment]
I believe that `raw_w` is the image width, in pixels; that `4.2` is the focal length in millimetres; and that `12.8` is the sensor width in millimetres. I might not be right about those.

The thing confusing me is the `1 / 2.55` factor. This appears to be the sensor diagonal in inches? I am not sure if that's right at all, or if it is, how it fits in to the calculation.

**Comment by jere357** [comment]
have you found out the actual meaning of the magic numbers or maybe found some solution for ur phone settings ?

**Comment by reynoldscem** [comment]
> have you found out the actual meaning of the magic numbers or maybe found some solution for ur phone settings ?

I'm afraid I just got the calibration for my device from elsewhere.

**Comment by jere357** [comment]
Could you please elaborate a bit more? I'm stuck at trying to figure out what the focal length should be as a number what things are taken into account when calculating it

**Comment by chenhsuanlin** [comment]
Hi @reynoldscem @jere357, sorry for the late reply. `1/2.55` was the sensor size I got from [here](https://en.wikipedia.org/wiki/Exmor). An easier way might be to use the 26mm FF-equivalent focal length (see [here](https://www.phonearena.com/phones/Apple-iPhone-12_id11417)), and then get `3024 (#pixels in width) / 24mm * 26mm = 3276`, which would get you similar answers as in the code. I'm not entirely sure these are the right way to get the intrinsics (not an expert), but from my experience, the focal length usually doesn't need to be super accurate to get NeRF/BARF working.

**Comment by reynoldscem** [comment]
> Could you please elaborate a bit more? I'm stuck at trying to figure out what the focal length should be as a number what things are taken into account when calculating it

Sorry I didn't calculate it analytically. I've used estimates from ARKit and from COLMAP.

**Comment by reynoldscem** [comment]
> 

Thank you for the reply @chenhsuanlin
