### ISSUE TITLE
Documentation on the LLFF data scene?

### ISSUE THREAD

**Issue by franciscoWizz** [chenhsuanlin/bundle-adjusting-NeRF#4]
Hi Chen-Hsuan,

Do you have any documentation regarding how to set up another scene experiment? I did not found anything on the readme  nor in the paper.

I'm refering to this folders and files:
![Data_LLFF](https://user-images.githubusercontent.com/92826180/138166529-6de999fb-ba7d-4212-b120-87cb06e1dc0b.png)

Thanks in advance,

**Comment by chenhsuanlin** [comment]
Hi @franciscoWizz, for now we assume that the incoming frames from the sequence are all equally sized and specified in `self.raw_H` and `self.raw_W`. The yaml files specify how you would want to resize your images (`opt.data.image_size`), which would rescale your intrinsic parameters accordingly. Hope this helps!

**Comment by chenhsuanlin** [comment]
Closing for now, please feel free to reopen if you have further questions!
