### ISSUE TITLE
Unreasonable training result with nerf_blender_repr.yaml

### ISSUE THREAD

**Issue by qianmingduowan** [chenhsuanlin/bundle-adjusting-NeRF#40]
Hi,
I wish to replicate the results from the original NeRF paper， but when I train with nerf_blender_repr.yaml， I only get PSNR 26.38 on lego scene. It's lower than nerf_blender.yaml, which can get PSNR 29.19.
Is there any mistake on nerf_blender_repr.yaml? Hope for your response.

**Comment by chenhsuanlin** [comment]
Hi @qianmingduowan, thanks for catching this. It's probably coming from [here](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/model/nerf.py#L127-L129), as my evaluation was intended for getting quantitative results in the single MLP setting. A quick fix would be to replace `var.rgb` L127 with `var.rgb_fine`:
```python
rgb_map = var.rgb_fine.view(-1,opt.H,opt.W,3).permute(0,3,1,2) # [B,3,H,W]
```
and it should report numbers from the fine MLP (in the reproduction setting). I will push a fix in the coming days.
