### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'train_data'

### ISSUE THREAD

**Issue by XuLinFeng569212510** [chenhsuanlin/bundle-adjusting-NeRF#45]
When I run “extract_mesh.py”. It seems that there is no data loaded. What's the matter？
![image](https://user-images.githubusercontent.com/26673980/174748293-6f78cf53-a1b7-48eb-92e2-84724d2983b9.png)
At the same time, the external parameters of the program I run are as follows
“python extract_mesh.py --group=G1 --model=barf --yaml=barf_blender --name=First --data.scene=chair --data.val_sub= --resume”

**Comment by sangminkim-99** [comment]
I think `m.load_dataset(opt)` need to be called before build the network.
That part might be omitted when merging [this PR](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/pull/16).

@chenhsuanlin 
Is there any reason for removing that part?

**Comment by chenhsuanlin** [comment]
Hi @XuLinFeng569212510, please add the following in `extract_mesh.py` as suggested by @sangminkim-99 :
```python
m.load_dataset(opt, eval_split="test")
```
I probably messed up when merging #16 -- sorry for the confusion! I will leave the issue open until I find time to push a fix.
