### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by lllz815** [chenhsuanlin/bundle-adjusting-NeRF#48]
after i train a barf and a image align model ,i get a .ckpt file  ,how i can use the model  or test the model

**Comment by chenhsuanlin** [comment]
Hi @lllz815, you should run `python3 evaluate.py [--args]`; please see the README for details.

**Comment by lllz815** [comment]
> Hi @lllz815, you should run `python3 evaluate.py [--args]`; please see the README for details.
thank for your replying ,now i train a barf with some picture which is taked by my ( xiao mi) phone ,i use the  iphone.py  and  i  do'nt  know how to compute th focal ,so use raw_W*4.2/(12.8/2.55) as you  ,but i finally get a bad result
 i use the follow commend to train  
python train.py --group=barf --model=barf --yaml=barf_iphone --name=iphone2 --data.scene=chair  --arch.posenc!
and the  follow commend to evaluate
python evaluate.py  --group=barf --model=barf --yaml=barf_iphone --name=iphone2 --data.scene=chair  --resume=10000  --arch.posenc!
my images are like this
![32](https://user-images.githubusercontent.com/101075695/177679375-fdcdf812-386a-411b-b2fd-720d3f89971c.jpg)
after evalate ,getting the result 
![depth_14](https://user-images.githubusercontent.com/101075695/177679514-4bf9facb-4f3f-44a5-b1e8-6ef9ff3536f3.png)
![rgb_14](https://user-images.githubusercontent.com/101075695/177679519-f0c38430-3d46-43f6-8eec-753efd3750d7.png)

for this result ,can  can you give me some suggettion ,thanks very much!

**Comment by lllz815** [comment]
> Hi @lllz815, you should run `python3 evaluate.py [--args]`; please see the README for details.

thank for your replying ,now i train a barf with some picture which is taked by my ( xiao mi) phone ,i use the iphone.py and i do'nt know how to compute th focal ,so use raw_W*4.2/(12.8/2.55) as you ,but i finally get a bad result
i use the follow commend to train
python train.py --group=barf --model=barf --yaml=barf_iphone --name=iphone2 --data.scene=chair --arch.posenc!
and the follow commend to evaluate
python evaluate.py --group=barf --model=barf --yaml=barf_iphone --name=iphone2 --data.scene=chair --resume=10000 --arch.posenc!
my images are like this  
![14](https://user-images.githubusercontent.com/101075695/177682861-10fd7aa2-ff9b-4cb5-a351-3bdf34842b9b.jpg)
and after evaluate get the result
![depth_14](https://user-images.githubusercontent.com/101075695/177682905-b49bb2f7-4165-429b-bdda-0b6c9bf41e7d.png)
![rgb_14](https://user-images.githubusercontent.com/101075695/177682910-53ac5a66-7c9c-4032-8d45-c56bfbe3caff.png)

for this result ,canyou give me some suggesttions ,thanks very much!!

**Comment by chenhsuanlin** [comment]
Are you trying to capture the chair with an object-centric sequence? If so, you may want to check out some previous discussions (e.g. #19, #32). BARF will probably be unable to automagically find the camera poses from scratch if the scenes were not simple forward-facing; you may need to run COLMAP to find a good pose initialization first.
