### ISSUE TITLE
Question about camera pose transformation for LLFF

### ISSUE THREAD

**Issue by t2kasa** [chenhsuanlin/bundle-adjusting-NeRF#5]
Hi, Chen-Hsuan Lin.
Thank you for sharing the great work!

I have been reading the code and I did not understand very well about camera pose transformation when calling `__getitem__` method for LLFF dataset:
https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/data/llff.py#L104

In my understanding, camera pose in returned values from `parse_cameras_and_bounds` is camera-to-world matrix and its coordinate system is [right, up, backwards].
https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/data/llff.py#L42

Then, the camera pose is transformed by `parse_raw_camera` when calling `__getitem__`, but I could not follow what the transformation did:
https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/main/data/llff.py#L104
Could you please let me know?

**Comment by chenhsuanlin** [comment]
Hi @t2kasa, I may need to dig back into the original NeRF repo to double-check their pose format and how I preprocessed it back then, but I don't really have the cycles for it at this moment. However, what I can tell you is that the output of `parse_raw_camera()` function is  guaranteed to be in the standard extrinsic matrix format of [right, down, forwards].
Sorry for the confusion!

**Comment by t2kasa** [comment]
Thank you.
It is helpful and enough to know that the output of `parse_raw_camera()` is the extrinsic matrix of [right, down, forwards]. I will try to track the transformations again later.

Thank you again!
