### ISSUE TITLE
What does the numbers in get_camera() mean?

### ISSUE THREAD

**Issue by JayPritchet** [chenhsuanlin/bundle-adjusting-NeRF#54]
Thanks for the wonderful project.
I wonder what does these numbers mean, and should I change them when testing my own dataset?
https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/803291bd0ee91c7c13fb5cc42195383c5ade7d15/data/iphone.py#L65

**Comment by chenhsuanlin** [comment]
Hi @JayPritchet, `self.focal` is the focal length of the camera for your dataset. Please see #39 for related discussions.

**Comment by ishrat-tl** [comment]
@chenhsuanlin Do we need focal length for inference as well? I thought that the model infers all the intrinsic parameters from the sequence during test time.

**Comment by chenhsuanlin** [comment]
Hi @ishrat-tl, the model does not infer intrinsic parameters. Both the camera intrinsic and extrinsic parameters (pose) have to be set for an image to be rendered.
