### ISSUE TITLE
how to visualize positional encoding  in visdom?

### ISSUE THREAD

**Issue by thekaka** [chenhsuanlin/bundle-adjusting-NeRF#55]
Figure 5 in the paper shows NeRF naive postinal encoding result, which displays the GT pose and refine pose of full postional encoding.

I looked into nerf part codes, but there is no relevant ones. 

https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/803291bd0ee91c7c13fb5cc42195383c5ade7d15/model/nerf.py#L89

Visulization function in nerf.py only supports Tensorbord but not includes visdom like barf.py.

It would be great if you could provide some suggestion about this issue. thx a lot

**Comment by chenhsuanlin** [comment]
Hi @thekaka, `nerf.py` in the codebase is for NeRF where cameras are fixed and non-optimizable. For the full positional encoding baseline, please use `barf.py` without the `--barf_c2f` argument (see README for more details).
