### ISSUE TITLE
initial camera parameters

### ISSUE THREAD

**Issue by shidilrzf** [chenhsuanlin/bundle-adjusting-NeRF#59]
Hi @chenhsuanlin,

Thanks for great work. I have some initial estimates of camera parameters from some of my own images. I wanted to use the blender dataset and I was wondering if I understand correctly that the transform_matrix in transforms_train.json for each frame is the camera extrinsic parameter in the form of [R | t], right?

**Comment by chenhsuanlin** [comment]
Hi @shidilrzf, the camera extrinsic matrices (`[R|t]`) correspond to the output of `get_camera()`. The entry `transform_matrix` from the Blender dataset is in another convention. Please see the [NeRF repo](https://github.com/bmild/nerf) for details.
