### ISSUE TITLE
success in nerf-pytorch but failed in barf

### ISSUE THREAD

**Issue by Zmy6** [chenhsuanlin/bundle-adjusting-NeRF#60]
Hi, i assume a list of  poses include extrinic parameters and intrinic parameters and run success in pytorch-nerf i can see the result of the nerf to prove my poses, but when i include this poses that i run successfully in nerf in barf i cannot get any useful informations, how i adjuct to fix it, can you give me some addvices about above, thanks a lot
in addition the form of poses that i assume is llff.

**Comment by chenhsuanlin** [comment]
Hi @Zmy6, can you elaborate on what problems you're trying to solve, what issues you're running into? I don't have enough context to provide useful suggestions.
