### ISSUE TITLE
The experiment about Fig. 8 in the paper

### ISSUE THREAD

**Issue by XinhuaZhang** [chenhsuanlin/bundle-adjusting-NeRF#63]
Hi Chen-Hsuan,

I trained a barf on the fern scene. I am not sure if the results below agree with SfM. In figure 8 I don't see the distance between the estimated poses and the ground truth poses. Is this normal?

![newplot (14)](https://user-images.githubusercontent.com/13424774/206050094-324fb94e-0f61-4395-864e-6048595ebf82.png)

**Comment by chenhsuanlin** [comment]
Hi @XinhuaZhang, the poses here are the raw optimized poses and are variable up to a 3D similarity transformation. The poses in Fig 8 are Procrustes aligned. Please see the `Evaluation criteria` section in the paper for details.

**Comment by XinhuaZhang** [comment]
Thanks
