### ISSUE TITLE
Why not use ndc in LLFF dataset?

### ISSUE THREAD

**Issue by Nemo1999** [chenhsuanlin/bundle-adjusting-NeRF#66]
Hi @chenhsuanlin 

Thanks for releasing the greate implementation, the codebase structure is very useful and extensible! 

I am trying to merge barf with voxel based nerf, and I noticed that you didn't use ndc in llff dataset.
Is there a reason for this choice? 
Do you see any factor preventing me from running barf with ndc on  LLFF ?  
Thank you very much!

**Comment by chenhsuanlin** [comment]
Hi @Nemo1999, when in the very early development stages, empirically I found that reparametrizing the 3D space with NDC did not work well with BARF. I have not got to revisit it after the final code release. If you happen to find interesting results with NDC, please do let me know! ☺️

**Comment by Nemo1999** [comment]
Thanks for the reply! I'll try that!

**Comment by panxkun** [comment]
> Thanks for the reply! I'll try that!

Hi，Do you have any findings on how NDC affects in Barf?

**Comment by Nemo1999** [comment]
Barf performs Very Bad with NDC. 
I think that is because NDC distort the original pose gradient.
