### ISSUE TITLE
Codes that Convert COLMAP Outputs to poses_bounds.npy

### ISSUE THREAD

**Issue by XinhuaZhang** [chenhsuanlin/bundle-adjusting-NeRF#69]
Hello, I would like to do the llff experiment with my own data and colmap poses. I found out that in data/llff.py, it read poses_bounds.npy instead of colmap outputs. I could not find the Python scripts that convert COLMAP outputs. I wrote one by using the functions provided by the LLFF dataset https://github.com/Fyusion/LLFF/tree/master/llff . The reconstruction quality was poor. I used other NeRF codes to learn a NeRF and the reconstruction were good. I am suspecting that there is something wrong with the poses_bounds.npy that was computed by the codes that I wrote. Could you tell me to how to create the poses_bounds.npy please? If there is already a file that does the job, could you point me to it please? Thanks!

**Comment by chenhsuanlin** [comment]
Hi @XinhuaZhang, the `pose_bounds.py` files I have been using are all preprocessed and provided by the datasets. The `gen_poses()` function [here](https://github.com/Fyusion/LLFF/blob/master/llff/poses/pose_utils.py#L259-L284) is probably what you're looking for. Hope this helps!

**Comment by zf-666** [comment]
I meet the same problem , have you fixed it? thanku
