### ISSUE TITLE
Training BARF with few views

### ISSUE THREAD

**Issue by jytime** [chenhsuanlin/bundle-adjusting-NeRF#71]
Hi,

Thanks for your great work! I am trying to apply BARF to a few-view setting, e.g., with 8 or 15 frames per sequence for training. The sequence is object-centric, with a trajectory of fly-around. I have initial camera poses for the frames, whose pair-wise relative rotation error is around 5 degrees. I was wondering if you have had prior experience training BARF with a few-view setting, or if there are any specific precautions I should be mindful of?

Best,
Jianyuan

**Comment by chenhsuanlin** [comment]
Hi @jytime, the LLFF scenes in the experiments had around 20-50 images, so I guess on the lower end, it's already somewhat close to your few-view setup. I have not tried fewer than 10 images, but the coarse-to-fine optimization in BARF should also help regularize the lack of data term. If you find any interesting observations, please let me know 🙂
