### ISSUE TITLE
ValueError: Expected a torch.device with a specified index or an integer, but got:cuda

### ISSUE THREAD

**Issue by danielchiu615** [chenhsuanlin/bundle-adjusting-NeRF#73]
(barf-env) C:\Users\usera\bundle-adjusting-NeRF>python3 train.py --group=test --model=barf --yaml=barf_llff --name=fern --data.scene=fern --barf_c2f=[0.1,0.5]
Process ID: 21644
[train.py] (PyTorch code for training NeRF/BARF)
setting configurations...
loading options/base.yaml...
loading options/nerf_llff.yaml...
loading options/barf_llff.yaml...
* H: 480
* W: 640
* arch:
   * density_activ: softplus
   * layers_feat: [None, 256, 256, 256, 256, 256, 256, 256, 256]
   * layers_rgb: [None, 128, 3]
   * posenc:
      * L_3D: 10
      * L_view: 4
   * skip: [4]
   * tf_init: True
* barf_c2f: [0.1, 0.5]
* batch_size: None
* camera:
   * model: perspective
   * ndc: False
   * noise: None
* cpu: False
* data:
   * augment:
   * center_crop: None
   * dataset: llff
   * image_size: [480, 640]
   * num_workers: 4
   * preload: True
   * root: None
   * scene: fern
   * train_sub: None
   * val_on_test: False
   * val_ratio: 0.1
   * val_sub: None
* device: cpu
* freq:
   * ckpt: 5000
   * scalar: 200
   * val: 2000
   * vis: 1000
* gpu: 0
* group: test
* load: None
* loss_weight:
   * render: 0
   * render_fine: None
* max_epoch: None
* max_iter: 200000
* model: barf
* name: fern
* nerf:
   * density_noise_reg: None
   * depth:
      * param: inverse
      * range: [1, 0]
   * fine_sampling: False
   * rand_rays: 2048
   * sample_intvs: 128
   * sample_intvs_fine: None
   * sample_stratified: True
   * setbg_opaque: None
   * view_dep: True
* optim:
   * algo: Adam
   * lr: 0.001
   * lr_end: 0.0001
   * lr_pose: 0.003
   * lr_pose_end: 1e-05
   * sched:
      * gamma: None
      * type: ExponentialLR
   * sched_pose:
      * gamma: None
      * type: ExponentialLR
   * test_iter: 100
   * test_photo: True
   * warmup_pose: None
* output_path: output/test/fern
* output_root: output
* resume: False
* seed: 0
* tb:
   * num_images: [4, 8]
* visdom:
   * cam_depth: 0.2
   * port: 9000
   * server: localhost
* yaml: barf_llff
existing options file found (identical)
Traceback (most recent call last):
  File "C:\Users\usera\bundle-adjusting-NeRF\train.py", line 32, in <module>
    main()
  File "C:\Users\usera\bundle-adjusting-NeRF\train.py", line 18, in main
    with torch.cuda.device(opt.device):
  File "C:\Users\usera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\cuda\__init__.py", line 312, in __init__
    self.idx = _get_device_index(device='cuda')
  File "C:\Users\usera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\cuda\_utils.py", line 36, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
  File "C:\Users\usera\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\_utils.py", line 731, in _get_device_index
    raise ValueError(
ValueError: Expected a torch.device with a specified index or an integer, but got:cuda
----------------------------------------------------------------------
I first typed git clone <github link>
then followed the steps and stuck here
I want to try this code with custom images with camera parameters
Appreciate any help!

**Comment by chenhsuanlin** [comment]
Hi @danielchiu615, the `device` in the config is `cpu`, which means your Pytorch is not correctly supporting cuda. You may want to double-check your installation, and you can verify with `torch.cuda.is_available()`.
