### ISSUE TITLE
about se3_refine parameter

### ISSUE THREAD

**Issue by pcc1016** [chenhsuanlin/bundle-adjusting-NeRF#77]
Hello! I'm a student studying NeRF, and I have a question about the SE3_refine function in the BARF code. I'm not sure what the parameters of 6-DoF refer to. Are they related to affine transformation? I'm not entirely certain. 

And regarding automatic backward, how do you know the Jacobian formula of the model and how do you compute automatic backward? I want to implement backward myself but I don't understand it well

Thank you for your research.

**Comment by chenhsuanlin** [comment]
Hi @pcc1016, [rigid transformations](https://en.wikipedia.org/wiki/Rigid_transformation) (in the SE(3) space) have 6 degrees of freedom (3 for rotation and 3 for translation). The gradients are computed via autodiff with PyTorch in practice.
