### ISSUE TITLE
why rescale weight of first layer if in barf mode

### ISSUE THREAD

**Issue by leo-frank** [chenhsuanlin/bundle-adjusting-NeRF#78]
Hi, great work on NeRF. I am interested in these lines, can you tell me: **why rescale weight of first layer if in barf mode**
               
                
https://github.com/chenhsuanlin/bundle-adjusting-NeRF/blob/803291bd0ee91c7c13fb5cc42195383c5ade7d15/model/planar.py#L211

Thank you very much for such amazing observation on gradient !

**Comment by chenhsuanlin** [comment]
Hi @leo-frank, this allows the initial optimization behavior to be equivalent to an MLP where the first layer consumes only a 2-dimensional input. This is very subtle though, and I don't really find it to make a big difference in practice.
