### ISSUE TITLE
I encountered some problems when I reproduced

### ISSUE THREAD

**Issue by Lijingbohere** [chenhsuanlin/bundle-adjusting-NeRF#79]
ImportError: cannot import name 'pytorch_ssim' from 'external.pohsun_ssim' (unknown location)。

**Comment by Lijingbohere** [comment]
(barf) lijingbo@Super-Server:~/bundle-adjusting-NeRF-main$ python3 train.py --group=LLFF --model=barf --yaml=barf_llff --name=room --data.scene=room --barf_c2f=[0.1,0.5]
Process ID: 943114
[train.py] (PyTorch code for training NeRF/BARF)
setting configurations...
loading options/base.yaml...
loading options/nerf_llff.yaml...
loading options/barf_llff.yaml...
* H: 480
* W: 640
* arch:
   * density_activ: softplus
   * layers_feat: [None, 256, 256, 256, 256, 256, 256, 256, 256]
   * layers_rgb: [None, 128, 3]
   * posenc:
      * L_3D: 10
      * L_view: 4
   * skip: [4]
   * tf_init: True
* barf_c2f: [0.1, 0.5]
* batch_size: None
* camera:
   * model: perspective
   * ndc: False
   * noise: None
* cpu: False
* data:
   * augment:
   * center_crop: None
   * dataset: llff
   * image_size: [480, 640]
   * num_workers: 4
   * preload: True
   * root: /data_home/home/lijingbo/NeRF_Data/nerf_llff_data
   * scene: room
   * train_sub: None
   * val_on_test: False
   * val_ratio: 0.1
   * val_sub: None
* device: cuda:0
* freq:
   * ckpt: 5000
   * scalar: 200
   * val: 2000
   * vis: 1000
* gpu: 0
* group: LLFF
* load: None
* loss_weight:
   * render: 0
   * render_fine: None
* max_epoch: None
* max_iter: 200000
* model: barf
* name: room
* nerf:
   * density_noise_reg: None
   * depth:
      * param: inverse
      * range: [1, 0]
   * fine_sampling: False
   * rand_rays: 2048
   * sample_intvs: 128
   * sample_intvs_fine: None
   * sample_stratified: True
   * setbg_opaque: None
   * view_dep: True
* optim:
   * algo: Adam
   * lr: 0.001
   * lr_end: 0.0001
   * lr_pose: 0.003
   * lr_pose_end: 1e-05
   * sched:
      * gamma: None
      * type: ExponentialLR
   * sched_pose:
      * gamma: None
      * type: ExponentialLR
   * test_iter: 100
   * test_photo: True
   * warmup_pose: None
* output_path: output/LLFF/room
* output_root: output
* resume: False
* seed: 0
* tb:
   * num_images: [4, 8]
* visdom:
   * cam_depth: 0.2
   * port: 9000
   * server: localhost
* yaml: barf_llff
existing options file found (identical)
Traceback (most recent call last):
  File "/home/lijingbo/bundle-adjusting-NeRF-main/train.py", line 32, in <module>
    main()
  File "/home/lijingbo/bundle-adjusting-NeRF-main/train.py", line 20, in main
    model = importlib.import_module("model.{}".format(opt.model))
  File "/home/lijingbo/anaconda3/envs/barf/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lijingbo/bundle-adjusting-NeRF-main/model/barf.py", line 14, in <module>
    from . import nerf
  File "/home/lijingbo/bundle-adjusting-NeRF-main/model/nerf.py", line 11, in <module>
    from external.pohsun_ssim import pytorch_ssim
ImportError: cannot import name 'pytorch_ssim' from 'external.pohsun_ssim' (unknown location)

**Comment by Timber-Ye** [comment]
It seems that you probably forget to add the Git submodule, which can be done by
```bash
git submodule init
git submodule update
```

**Comment by chenhsuanlin** [comment]
Thanks @Timber-Ye. Please follow the README to initialize the submodules with
```bash
git submodule update --init --recursive
```
