### ISSUE TITLE
Bundle-Adjusting Neural Radiance Fields

### ISSUE THREAD

**Issue by Lijingbohere** [chenhsuanlin/bundle-adjusting-NeRF#80]
Is the weighting parameter α random or does it vary according to a regular pattern?
![image](https://github.com/chenhsuanlin/bundle-adjusting-NeRF/assets/75312149/a1d7a5d6-16d6-43b5-85cf-088d2ac111fc)

**Comment by chenhsuanlin** [comment]
Hi @Lijingbohere, it is (heuristically) controlled as a function of the optimization progress. Please see the experiments section in the paper for details.
